services:
  - type: web
    name: spotus-notifications
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: ~20.0.0
      - key: PORT
        value: 8080
